### ISSUE TITLE
Have template for Google?

### ISSUE THREAD

**Issue by Dazmed707** [ngn13/pufferphish#1]
Support Google and bypass 2fa/Mfa?

**Comment by ngn13** [comment]
There is no template for google, if you have the time and the knowledge you can create one, or you can wait until I create one (I'm currently busy with other stuff so you will have to wait a bit)

And no it does not "bypass" MFA, this tool just serves a fake page that captures username and password that the user enter. If you want to bypass MFA and compromise user accounts, I suggest you check out [evilginx](https://github.com/kgretzky/evilginx2), it is kinda hard to configure, so [here is a repo](https://github.com/An0nUD4Y/Evilginx2-Phishlets) containing pre-built configurations.

**Comment by Dazmed707** [comment]
Those evilginx phishlet don't work 

I have a google phishlet but it detects me and I can't move forward. 

I got it to configure evilginx
But I need to update my google phishlet

**Comment by ngn13** [comment]
I cannot help you with evilginx phishlets, if you are having issues, you should ask other people, in other places, this is not the place for it
